# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Parsing framework based on conduit"
HOMEPAGE="https://github.com/k0ral/conduit-parse"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE=""	# FIXME: license unknown to cabal. Please pick it manually.
SLOT="0/${PV}"
KEYWORDS="amd64 ~x86"
IUSE="enable-hlint-test"

RDEPEND=">=dev-haskell/conduit-1.3:=[profile?]
	dev-haskell/dlist:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/parsers:=[profile?]
	dev-haskell/safe:=[profile?]
	dev-haskell/safe-exceptions:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-lang/ghc-7.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
	test? ( dev-haskell/resourcet
		dev-haskell/tasty
		dev-haskell/tasty-hunit
		enable-hlint-test? ( dev-haskell/hlint ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag enable-hlint-test enable-hlint-test)
}
