# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="detect mismatches between compile-time and run-time versions of the ghc api"
HOMEPAGE="http://hackage.haskell.org/package/ghc-check"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="amd64 ~x86"
IUSE="+ghc-check-use-package-abis"

RDEPEND="dev-lang/ghc:=[profile?]
	dev-haskell/ghc-paths:=[profile?]
	dev-haskell/safe-exceptions:=[profile?]
	>=dev-lang/ghc-8.2.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0.0.2
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag ghc-check-use-package-abis ghc-check-use-package-abis)
}
