# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Explicit imports plugin for Haskell Language Server"
HOMEPAGE="http://hackage.haskell.org/package/hls-explicit-imports-plugin"
SRC_URI="https://github.com/haskell/haskell-language-server/archive/0.7.1.tar.gz -> haskell-language-server-0.7.1.tar.gz"

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS="amd64 ~x86"
IUSE=""
S=${WORKDIR}/haskell-language-server-0.7.1/plugins/${PN}

RDEPEND="dev-haskell/aeson:=[profile?]
	dev-lang/ghc:=[profile?]
	dev-haskell/ghcide:=[profile?]
	dev-haskell/haskell-lsp-types:=[profile?]
	dev-haskell/hls-plugin-api:=[profile?]
	dev-haskell/shake:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2
"
