# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.2

EAPI=7

CRATES="
	aho-corasick-0.7.10
	annotate-snippets-0.8.0
	ansi_term-0.11.0
	arrayvec-0.7.0
	atty-0.2.14
	autocfg-1.0.0
	bitflags-1.2.1
	block-buffer-0.9.0
	cc-1.0.53
	cfg-if-0.1.10
	cfg-if-1.0.0
	clap-2.33.0
	cloudabi-0.1.0
	cpuid-bool-0.1.2
	crossbeam-deque-0.7.3
	crossbeam-epoch-0.8.2
	crossbeam-queue-0.2.3
	crossbeam-utils-0.7.2
	crossbeam-utils-0.8.4
	derive_more-0.99.5
	digest-0.9.0
	either-1.5.3
	ena-0.14.0
	env_logger-0.7.1
	generic-array-0.14.4
	getopts-0.2.21
	getrandom-0.2.2
	hashbrown-0.8.2
	hermit-abi-0.1.10
	humantime-1.3.0
	humantime-2.0.0
	indexmap-1.5.2
	instant-0.1.7
	itoa-0.4.5
	jobserver-0.1.21
	lazy_static-1.4.0
	lazycell-1.2.1
	libc-0.2.77
	lock_api-0.4.4
	log-0.4.8
	maybe-uninit-2.0.0
	md-5-0.9.1
	measureme-9.1.0
	memchr-2.3.3
	memmap-0.7.0
	memmap2-0.2.2
	memoffset-0.5.4
	num_cpus-1.12.0
	opaque-debug-0.3.0
	parking_lot-0.11.0
	parking_lot_core-0.8.0
	perf-event-open-sys-1.0.1
	ppv-lite86-0.2.10
	proc-macro2-1.0.10
	psm-0.1.8
	quick-error-1.2.3
	quote-1.0.3
	rand-0.8.3
	rand_chacha-0.3.0
	rand_core-0.6.2
	rand_hc-0.3.0
	redox_syscall-0.1.56
	redox_syscall-0.2.7
	regex-1.3.6
	regex-syntax-0.6.17
	remove_dir_all-0.5.2
	rls-span-0.5.2
	rustc-ap-rustc_arena-722.0.0
	rustc-ap-rustc_ast-722.0.0
	rustc-ap-rustc_ast_pretty-722.0.0
	rustc-ap-rustc_data_structures-722.0.0
	rustc-ap-rustc_errors-722.0.0
	rustc-ap-rustc_feature-722.0.0
	rustc-ap-rustc_fs_util-722.0.0
	rustc-ap-rustc_graphviz-722.0.0
	rustc-ap-rustc_index-722.0.0
	rustc-ap-rustc_lexer-722.0.0
	rustc-ap-rustc_lint_defs-722.0.0
	rustc-ap-rustc_macros-722.0.0
	rustc-ap-rustc_parse-722.0.0
	rustc-ap-rustc_serialize-722.0.0
	rustc-ap-rustc_session-722.0.0
	rustc-ap-rustc_span-722.0.0
	rustc-ap-rustc_target-722.0.0
	rustc-hash-1.1.0
	rustc-rayon-0.3.1
	rustc-rayon-core-0.3.1
	ryu-1.0.3
	scoped-tls-1.0.0
	scopeguard-1.1.0
	serde-1.0.105
	serde_derive-1.0.105
	serde_json-1.0.50
	sha-1-0.9.2
	sha2-0.9.2
	smallvec-1.6.1
	stable_deref_trait-1.1.1
	stacker-0.1.12
	strsim-0.8.0
	syn-1.0.17
	synstructure-0.12.3
	tempfile-3.2.0
	termcolor-1.1.0
	termize-0.1.1
	textwrap-0.11.0
	thread_local-1.0.1
	tracing-0.1.19
	tracing-attributes-0.1.11
	tracing-core-0.1.15
	typenum-1.12.0
	unicode-normalization-0.1.12
	unicode-width-0.1.7
	unicode-xid-0.2.0
	vec_map-0.8.1
	version_check-0.9.2
	wasi-0.10.2+wasi-snapshot-preview1
	winapi-0.3.8
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.4
	winapi-x86_64-pc-windows-gnu-0.4.0
 	${P}
	racer-cargo-metadata-0.1.2
	racer-interner-0.1.0
"

inherit cargo

DESCRIPTION="Code completion for Rust"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/racer-rust/racer"
SRC_URI="$(cargo_crate_uris ${CRATES})"
BDEPEND=">=dev-lang/rust-1.55[nightly]"
PATCHES=("${FILESDIR}"/remove-testutils.patch)

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Apache-2.0 BSD-2 BSD-4 BSL-1.1 MIT Unlicense"
SLOT="0"
KEYWORDS="amd64"
RESTRICT="mirror"
