# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Haskell Lindenmayer Systems"
HOMEPAGE="http://rd.slavepianos.org/t/hls"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE=""	# FIXME: license unknown to cabal. Please pick it manually.
SLOT="0/${PV}"
KEYWORDS="amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/hcg-minus-0.15:=[profile?] <dev-haskell/hcg-minus-0.16:=[profile?]
	>=dev-haskell/hps-0.15:=[profile?] <dev-haskell/hps-0.16:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"
