# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6

CABAL_FEATURES=""
inherit haskell-cabal

DESCRIPTION="Open haddock HTML documentation"
HOMEPAGE="http://hackage.haskell.org/package/open-haddock"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/basic-prelude-0.5:=
	>=dev-haskell/text-1.2:=
	>=dev-haskell/turtle-1.2:=
	>=dev-lang/ghc-7.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
"
src_prepare() {
	default

	cabal_chdeps \
		'base >=4.8 && <4.9' 'base >= 4.8'
}