# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Backend for the persistent library using sqlite3"
HOMEPAGE="http://www.yesodweb.com/book/persistent"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="amd64 ~x86"
IUSE="build-sanity-exe +full-text-search +have-usleep +json1 pkgconfig stat3 +stat4 systemlib +uri-filenames"

RDEPEND=">=dev-haskell/aeson-1.0:=[profile?]
	>=dev-haskell/conduit-1.2.12:=[profile?]
	>=dev-haskell/microlens-th-0.4.1.1:=[profile?]
	>=dev-haskell/monad-logger-0.3.25:=[profile?]
	>=dev-haskell/persistent-2.11:=[profile?] <dev-haskell/persistent-3:=[profile?]
	dev-haskell/resource-pool:=[profile?]
	>=dev-haskell/resourcet-1.1.9:=[profile?]
	>=dev-haskell/text-1.2:=[profile?]
	dev-haskell/unliftio-core:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	>=dev-lang/ghc-8.0.1:=
	virtual/libc
	systemlib? ( pkgconfig? ( unknown-pkg-config/sqlite3 )
			!pkgconfig? ( >=dev-db/sqlite-3.0 ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.24.0.0
	test? ( dev-haskell/exceptions
		dev-haskell/fast-logger
		>=dev-haskell/hspec-2.4
		dev-haskell/hunit
		dev-haskell/persistent-template
		dev-haskell/persistent-test
		dev-haskell/quickcheck
		dev-haskell/system-fileio
		dev-haskell/system-filepath
		dev-haskell/temporary )
	pkgconfig? ( systemlib? ( virtual/pkgconfig ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag build-sanity-exe build-sanity-exe) \
		$(cabal_flag full-text-search full-text-search) \
		$(cabal_flag have-usleep have-usleep) \
		$(cabal_flag json1 json1) \
		$(cabal_flag systemlib systemlib) \
		$(cabal_flag uri-filenames uri-filenames) \
		$(cabal_flag pkgconfig use-pkgconfig) \
		$(cabal_flag stat3 use-stat3) \
		$(cabal_flag stat4 use-stat4)
}
