# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="LSP server for GHC"
HOMEPAGE="https://github.com/haskell/haskell-language-server#readme"
SRC_URI="https://github.com/haskell/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz"

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS="amd64 ~x86"
IUSE="+agpl pedantic"

RDEPEND="dev-haskell/hls:=[profile?]
	>=dev-haskell/hls-plugin-api-0.5:=[profile?]
	dev-haskell/hls-explicit-imports-plugin:=[profile?]
	dev-haskell/hls-hlint-plugin:=[profile?]
	dev-haskell/hls-retrie-plugin:=[profile?]
	dev-haskell/hls-tactics-plugin:=[profile?]
	dev-haskell/aeson:=[profile?]
	dev-haskell/data-default:=[profile?]
	dev-haskell/extra:=[profile?]
	>=dev-haskell/floskell-0.10:=[profile?] <dev-haskell/floskell-0.11:=[profile?]
	>=dev-haskell/fourmolu-0.3:=[profile?] <dev-haskell/fourmolu-0.4:=[profile?]
	dev-lang/ghc:=[profile?]
	dev-haskell/ghc-paths:=[profile?]
	>=dev-haskell/ghcide-0.6.0.1:=[profile?]
	dev-haskell/gitrev:=[profile?]
	dev-haskell/hashable:=[profile?]
	>=dev-haskell/haskell-lsp-0.22:=[profile?] <dev-haskell/haskell-lsp-0.23:=[profile?]
	dev-haskell/hie-bios:=[profile?]
	dev-haskell/hslogger:=[profile?]
	dev-haskell/lens:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/optparse-applicative:=[profile?]
	dev-haskell/optparse-simple:=[profile?]
	>=dev-haskell/ormolu-0.1.2:=[profile?] <dev-haskell/ormolu-0.2:=[profile?]
	dev-haskell/regex-tdfa:=[profile?]
	dev-haskell/safe-exceptions:=[profile?]
	>=dev-haskell/shake-0.17.5:=[profile?]
	>=dev-haskell/stylish-haskell-0.12:=[profile?] <dev-haskell/stylish-haskell-0.13:=[profile?]
	dev-haskell/temporary:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	>=dev-lang/ghc-8.6.3:=
	agpl? ( >=dev-haskell/brittany-0.13.1.0:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.4.0.1
	test? ( dev-haskell/blaze-markup
		dev-haskell/hspec
		dev-haskell/hspec-core
		>=dev-haskell/lsp-test-0.11.0.6
		dev-haskell/stm
		dev-haskell/tasty
		>=dev-haskell/tasty-ant-xml-1.1.6
		dev-haskell/tasty-expected-failure
		dev-haskell/tasty-golden
		dev-haskell/tasty-hunit
		dev-haskell/tasty-rerun
		dev-haskell/yaml )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag agpl agpl) \
		$(cabal_flag pedantic pedantic)
}
