# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Auto generate hie-bios cradles & hie.yaml"
HOMEPAGE="https://github.com/Avi-D-coder/implicit-hie#readme"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/attoparsec-0.13:=[profile?]
	>=dev-haskell/filepattern-0.1:=[profile?]
	>=dev-haskell/text-1.2:=[profile?]
	>=dev-haskell/yaml-0.5:=[profile?]
	>=dev-lang/ghc-8.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0
	test? ( dev-haskell/hspec
		dev-haskell/hspec-attoparsec )
"
